### PR TITLE
PR: Fix loading Spydata file with changed filename and other edge-cases in load_dict

### LINKED ISSUE #9: Spydata files won't import if the original filename is changed
@TinyCloud commented on [Tue Jul 17 2018](https://github.com/spyder-ide/spyder/issues/7483)

## Problem Description
Whenever I've saved a session's data as a .spydata file and tried to import it at a later point in time, the behavior is highly erratic - works sometimes and does not do anything sometimes.

### What steps will reproduce the problem?
- Export a copy of the session dataframes and variables by Save as from Variable explorer . Ex: test.spydata in your working directory.
- Use import from variable explorer to open the same file. Does not always work.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.15
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 17.6.0

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

---

@ccordoba12 commented on [Tue Jul 17 2018](https://github.com/spyder-ide/spyder/issues/7483#issuecomment-405638147)

Moving to the right repo.

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Before this PR, ``.spydata`` files could not be loaded if their filename was changed from the original value. This PR fixes that and allows such files to be loaded. Additionally, it cleans up a few smaller issues/edge cases in the ``load_dict()`` function:

* It now catches and reports ``AttributeErrors`` loading files with pickled functions that aren't currently loaded in the ``__main__`` namespace
* It always makes sure to clean up its temp directory and reset the working dir even if an uncaught error occurs 
* It uses a context manager for the tar file and ensures it is closed and cleaned up properly (it wasn't before), and
* It removes ancient pre-Spyder-2.2 code for loading Python 2 namespaces saved with the nearly 6 year old Spyder 2.0 and 2.1, that resulted in a ``DeprecationWarning``, slowed down the load process and could cause uncaught errors

Additionally, it adds tests/test coverage for renamed files, files with errors that prevent them being loaded, and that the working directory is reset properly.

Fixes #9

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@ccordoba12 What's going on with ``test_cwd_in_sys_path()``? It fails on all builds on AppVeyor and CircleCI, including Windows/Py3.6/Anaconda like my system, but it passes just fine locally. I didn't actually add any ``os.chdir()`` calls, just make sure the ones that were already there fired when they were supposed to, and I even check that the working directory is reset properly after an error (when it wasn't before) so I'm not sure what's up.

**Comment by ccordoba12** [comment]
> What's going on with test_cwd_in_sys_path()?

The problem that that test was trying to catch was fixed upstream by the IPython guys in its **7.2.0** version.

So in master I simply skipped that test for `IPython >= 7.2.0`, as shown here:

https://github.com/spyder-ide/spyder-kernels/pull/71/files#diff-5ab143bf8d74af8d46fcbfe2ccf9ac0dR129

**Comment by CAM-Gerlach** [comment]
> So in master I simply skipped that test for IPython >= 7.2.0, as shown here:

Okay, so do you want me to add that here, then?

> Looks good to me but your new test (test_spydata_import_witherror) is failing in Python 2.

Just an issue with ``str`` vs. ``basestring``; didn't remember Python 2 had that. Hopefully fixed now.

**Comment by ccordoba12** [comment]
> Okay, so would you rather me add that here

Please do it here.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Done as requested. Sorry for the delay; I was at my university all day without my laptop dealing with some pressing issues.

**Comment by PraveenTumma** [comment]
Hello Christopher/Carlos, Good Evening!!

I tried to find the right thread for my issue but could not as some are showing as closed and some are showing as merged so I ended up here and want to report an issue am facing today. About 3 days back I exported my spyder variables into a .spydata file and was successful re-importing the file later and done some changes to the variables.

Today I exported it again with different name (except date change in the filename) and when I tried to import the new file and also old file (with older date in the filename), both are not getting imported and doing nothing.

The directory have full permissions in it and as mentioned, it worked before but not today. Only one thing I have done after exporting today is create a new env in anaconda and launched spyder from the new env and tried importing both new and old files but both failed. No error as such in any case. 

Then I opened the original anaconda env (base) from where I exported the variables but then also both file imports failed with no errors.

Pls let me know if there is any solution for it.

Here is my system configuration:

I have Spyder (3.3.3) with python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 64-bit

Details
```
(base) C:\Users\85033964>conda list
# packages in environment at C:\Users\85033964\AppData\Local\Continuum\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  2019.03                  py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.2                    py37_0
asn1crypto                0.24.0                   py37_0
astroid                   2.2.5                    py37_0
astropy                   3.1.2            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.1.0                   py37_1
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.7.1                    py37_1
bitarray                  0.8.3            py37hfa6e2cd_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.15.0               h7bd577a_0
bokeh                     1.0.4                    py37_0
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.1.23                     0
certifi                   2019.3.9                 py37_0
cffi                      1.12.2           py37h7a1dbc1_1
chardet                   3.0.4                    py37_1
click                     7.0                      py37_0
cloudpickle               0.8.0                    py37_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
comtypes                  1.1.7                    py37_0
conda                     4.6.14                   py37_0
conda-build               3.17.8                   py37_0
conda-env                 2.6.0                         1
conda-verify              3.1.1                    py37_0
console_shortcut          0.1.1                         3
contextlib2               0.5.5                    py37_0
cryptography              2.6.1            py37h7a1dbc1_0
cudatoolkit               10.0.130                      0
curl                      7.64.0               h2a8f88b_2
cycler                    0.10.0                   py37_0
cython                    0.29.6           py37ha925a31_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      1.1.4                    py37_1
dask-core                 1.1.4                    py37_1
decorator                 4.4.0                    py37_1
defusedxml                0.5.0                    py37_1
distributed               1.26.0                   py37_1
docutils                  0.14                     py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
filelock                  3.0.10                   py37_0
flask                     1.0.2                    py37_1
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py37_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glob2                     0.6                      py37_1
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                    py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.5.0                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.8                      py37_0
intel-openmp              2019.3                      203
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.4.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
isort                     4.3.16                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4                      py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.4.0                    py37_0
jupyterlab                0.35.4           py37hf63ae98_0
jupyterlab_server         0.2.0                    py37_0
keyring                   18.0.0                   py37_0
kiwisolver                1.0.1            py37h6538335_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libarchive                3.3.3                h0643e63_5
libcurl                   7.64.0               h2a8f88b_2
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.36               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                h7a1dbc1_4
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
llvmlite                  0.28.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.3.2            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.0.3            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.3                      203
mkl-service               1.1.2            py37hb782905_5
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
more-itertools            6.0.0                    py37_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.4.1                    py37_3
nbformat                  4.4.0                    py37_0
networkx                  2.2                      py37_1
ninja                     1.9.0            py37h74a9793_0
nltk                      3.4                      py37_1
nose                      1.3.7                    py37_2
notebook                  5.7.8                    py37_0
numba                     0.43.1           py37hf9181ef_0
numexpr                   2.6.9            py37hdce8814_0
numpy                     1.16.2           py37h19fb1c0_0
numpy-base                1.16.2           py37hc3f5095_0
numpydoc                  0.8.0                    py37_0
olefile                   0.46                     py37_0
openpyxl                  2.6.1                    py37_1
openssl                   1.1.1b               he774522_1
packaging                 19.0                     py37_0
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.3.4                    py37_0
partd                     0.3.10                   py37_1
path.py                   11.5.0                   py37_0
pathlib2                  2.3.3                    py37_0
patsy                     0.5.1                    py37_0
pep8                      1.7.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.4.1            py37hdc69c19_0
pip                       19.0.3                   py37_0
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.9.0                    py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
prometheus_client         0.6.0                    py37_0
prompt_toolkit            2.0.9                    py37_0
psutil                    5.6.1            py37he774522_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.2         py37h7a1dbc1_0
pyflakes                  2.1.1                    py37_0
pygments                  2.3.1                    py37_0
pylint                    2.3.1                    py37_0
pyodbc                    4.0.26           py37ha925a31_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.1                    py37_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.14.11          py37he774522_0
pysocks                   1.6.8                    py37_0
pytables                  3.5.1            py37h1da0976_0
pytest                    4.3.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.3.0                    py37_0
pytest-openfiles          0.3.2                    py37_0
pytest-remotedata         0.3.1                    py37_0
python                    3.7.3                h8c8aaf0_0
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                      py37_6
pytorch                   1.0.1           py3.7_cuda100_cudnn7_1    pytorch
pytz                      2018.9                   py37_0
pywavelets                1.0.2            py37h8c2d366_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1              py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.7                    py37_1
qtconsole                 4.4.3                    py37_0
qtpy                      1.7.0                    py37_1
requests                  2.21.0                   py37_0
rope                      0.12.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-image              0.14.2           py37ha925a31_0
scikit-learn              0.20.3           py37h343c172_0
scipy                     1.2.1            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
setuptools                40.8.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1                    py37_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.8                      py37_0
sphinx                    1.8.5                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    3.3.3                    py37_0
spyder-kernels            0.4.2                    py37_0
sqlalchemy                1.3.1            py37he774522_0
sqlite                    3.27.2               he774522_0
statsmodels               0.9.0            py37h452e1ab_0
sympy                     1.3                      py37_0
tblib                     1.3.2                    py37_0
terminado                 0.8.1                    py37_1
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py37_0
tornado                   6.0.2            py37he774522_0
tqdm                      4.31.1                   py37_1
traitlets                 4.3.2                    py37_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.33.1                   py37_0
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.1           py37he774522_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.1.5                    py37_0
xlwings                   0.15.4                   py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zict                      0.1.4                    py37_0
zipp                      0.3.3                    py37_1
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

(base) C:\Users\85033964>```

**Comment by CAM-Gerlach** [comment]
> Christopher

*CAM

> Good Evening!!

Its afternoon for me.

> I tried to find the right thread for my issue but could not as some are showing as closed and some are showing as merged so I ended up here and want to report an issue am facing today.

As you can see, this is a pull request that is already merged and closed, so nothing more can be done here. You need to open a new issue and fill out the template like everyone else, if yours is not directly related to an existing issue. Please also note the version of ``spyder-kernels`` you are running in your environment (you can find out with ``import spyder_kernels; print(spyder_kernels.__version__)``) and attach one of the files that don't work (preferably the smallest one) so we can test and reproduce it.

Thanks.

**Pull request merged**
