### PR TITLE
PR: Fix debugger depth

### PR DESCRIPTION
**Pull request by impact27**
Fix debugger depth and cleanup the frontend notification
Fixes https://github.com/spyder-ide/spyder-kernels/issues/330

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @impact27, how important do you think this is? I mean, is it worth to include it in our next release (2.2.0) that will be needed by Spyder 5.2.0?

**Comment by impact27** [comment]
I would say this is a minor inconvenance but it makes the code nicer. It is needed for the profiler PR#286

**Comment by ccordoba12** [comment]
@impact27, why did you decide to close this PR?

**Comment by impact27** [comment]
I had to change the logic of exec_code to conditionally return something, and so I decided to fix #330 there. This one is not needed anymore when https://github.com/spyder-ide/spyder-kernels/pull/355 is merged

**Pull request closed without merging**
