### PR TITLE
PR: Set Matplotlib backend to inline for kernels started outside Spyder

### LINKED ISSUE #108: Set matplotlib backend to inline by default on starting a new kernel
Opened by request of @ccordoba12 

``spyder-kernels`` should set the graphics backend to ``inline`` by default on starting a ``spyder-kernels`` kernel, to match the Spyder default and so plots work by default on remote machines over ``ssh``. Currently, in my testing, plots in such consoles appear in interactive mode (i.e. Qt backend), rather than inline.

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #108.

### CODE REVIEW

**Comment by ccordoba12** [comment]
> Its in Spyder 4 with external kernels where this matters, as the backend currently needs to be explicitly set to inline

Ok, I was not aware of that. I'll move it to master then.

**Comment by CAM-Gerlach** [comment]
Thanks; I should have been clearer and more explicit about that in my initial issue. I was in a rush to go somewhere so I wasn't as thorough as usual. I'll review this again.

**Comment by ccordoba12** [comment]
Ok, thanks for the confirmation. I still don't understand how things are working correctly for Spyder 3 and not for 4, so I'm going to move back this PR to `0.x` to be totally sure.

**Comment by CAM-Gerlach** [comment]
> I still don't understand how things are working correctly for Spyder 3 and not for 4

It has something to do with the Plots plugin and not displaying figures inline due to that, as far as I'm aware.

**Pull request merged**
